version: '3.5'

services:
  postgres:
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_MULTIPLE_DATABASES: lending,catalogue,lending_test,catalogue_test
      PGDATA: /data/postgres
    volumes:
      - ./db_data:/data/postgres
      - ./migrations/init:/docker-entrypoint-initdb.d

networks:
  be_network:
    driver: bridge