openapi: "3.0.2"
info:
  title: Lending Service
  version: "1.0"
servers:
  - url: http://{hostname}/api/v1
    description: Local server
    variables:
      hostname:
        default: localhost:8080
  - url: https://{hostname}/api/v1
    description: Secure HTTP Server
    variables:
      hostname:
        default: localhost

security:
  - bearerAuth: [ ]

paths:
  /patrons/{patronId}/holds:
    post:
      operationId: placeHold
      description: place hold a book
      tags:
        - Patron
      parameters:
        - in: path
          name: patronId
          schema:
            type: string
            minimum: 0
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: PlaceHoldRequest
              properties:
                bookId:
                  type: string
                numOfDays:
                  type: integer
              required:
                - bookId
                - numOfDays
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"
    delete:
      operationId: cancelHold
      description: cancel a hold
      tags:
        - Patron
      parameters:
        - in: path
          name: patronId
          schema:
            type: string
            minimum: 0
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: CancelHoldRequest
              properties:
                bookId:
                  type: string
              required:
                - bookId
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"

  /patrons/{patronId}/checkout:
    post:
      operationId: checkout
      description: checkout a book
      tags:
        - Patron
      parameters:
        - in: path
          name: patronId
          schema:
            type: string
            minimum: 0
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: CheckoutRequest
              properties:
                bookId:
                  type: string
              required:
                - bookId
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"

  /books/{bookId}/return:
    put:
      operationId: returnBook
      description: return a book
      tags:
        - Book
      parameters:
        - in: path
          name: bookId
          schema:
            type: string
            minimum: 0
          required: true
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    BaseResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message