pkgname = "models"
output = "adapters/models"
wipe = true
no-tests = true
add-enum-types = true
add-soft-deletes = true

[psql]
host = "localhost"
dbname = "lending"
user = "postgres"
pass = "changeme"
sslmode = "disable"
blacklist = ["schema_migrations"]